# name: Exploring Variables and Secrets

# on: push
# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build
#               run: docker build -t docker.io/sumeshgithub/nginx:latest

#             - name: Docker Login
#               run: docker login --username=sumeshgithub --password=$umesH@123
            
#             - name:  Docker Publish
#               run: docker push docker.io/sumeshgithub/nginx:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
                      
#             - name:  Docker Run
#               run: docker run -d -p 8080:80 docker.io/sumeshgithub/nginx:latest

# Environment variable as Step Level #

# name: Exploring Variables and Secrets

# on: push
# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: sumeshgithub               
#                 IMAGE_NAME: nginx
#                 IMAGE_VERSION: latest
#               run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION

#             - name: Docker Login
#               env:
#                 DOCKER_USERNAME: sumeshgithub
#                 DOCKER_PASSWORD: "$umesH@123"
#               run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            
#             - name:  Docker Publish
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: sumeshgithub               
#                 IMAGE_NAME: nginx
#                 IMAGE_VERSION: latest
#               run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
                      
#             - name:  Docker Run
#               env:
#                 CONTAINER_REGISTRY: docker.io
#                 DOCKER_USERNAME: sumeshgithub               
#                 IMAGE_NAME: nginx
#                 IMAGE_VERSION: latest
#               run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION


# Environment variable at job level 



# name: Exploring Variables and Secrets

# on: push
# jobs:
#     docker:
#         env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: sumeshgithub               
#             IMAGE_NAME: nginx
#             IMAGE_VERSION: latest            
            
#         runs-on: ubuntu-latest
#         steps:
#             - name: Docker Build              
#               run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION

#             - name: Docker Login          
#               env:
#                 DOCKER_PASSWORD: "$umesH@123"    
#               run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            
#             - name:  Docker Publish             
#               run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION

#     deploy:
#         env:
#             CONTAINER_REGISTRY: docker.io
#             DOCKER_USERNAME: sumeshgithub               
#             IMAGE_NAME: nginx
#             IMAGE_VERSION: latest
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
                      
#             - name:  Docker Run
              
#               run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION

# Environment variable at workflow level 



name: Exploring Variables and Secrets

on: push
env:
    CONTAINER_REGISTRY: hub.docker.com
    # DOCKER_USERNAME: sumeshgithub               
    IMAGE_NAME: nginx
    IMAGE_VERSION: latest  
    LOCAL_IMAGE_NAME: nginx_local
jobs:
    docker:                 
            
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: Docker Build              
              run: docker build -t ${{ env.LOCAL_IMAGE_NAME }} .

            - name: Tag Image
              run: docker tag ${{ env.LOCAL_IMAGE_NAME }} ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

            - name: Docker Login
              run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

            - name:  Docker Publish                         
              run: docker push ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

    deploy:
      
        needs: docker
        runs-on: ubuntu-latest
        steps:
                      
            - name:  Docker Run
              
              run: docker run --name sumesh -d -p 8080:80 ${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}

            - name: Check Localhost
              run: curl http://localhost

            - name: Show custom message
              run: curl http://localhost/index.html

            - name: Show content of Index file
              run: docker exec sumesh cat /usr/share/nginx/html/index.html
              
            - name: List Running Dockers
              run: docker ps



